{% set name = "argos" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/argos-{{ version }}.tar.gz
  sha256: 7c170dcfbef8e833f1928a6022c5d04874883d95383b9790f627f736f02c70cd

build:
  number: 0
  noarch: python
  entry_points:
    - argos = argos.main:main
    - argos_make_wrappers = argos.argos_make_wrappers:main
    - argosw = argos.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<3.10
  run:
    - cmlib >=1.1.2
    - numpy >=1.11
    - pgcolorbar >=1.1.0
    - pyqtgraph >=0.11
    - python >=3.7,<3.10

test:
  imports:
    - argos
    - argos.collect
  commands:
    - pip check
    - argos --help
    - argos_make_wrappers --help
    - argosw --help
  requires:
    - pip
    - pyqt >=5.12

about:
  home: https://github.com/titusjan/argos
  summary: Argos HDF5/NetCDF/scientific data viewer.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - titusjan
